"""Esquema inicial de tabela

Revision ID: 19f132fe4f61
Revises: 
Create Date: 2025-12-08 23:59:56.252038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19f132fe4f61'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_cbo',
    sa.Column('cod_cbo', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('cod_cbo')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_cbo')
    # ### end Alembic commands ###
